### ISSUE TITLE
IoTCOM errors from eclipse 

### ISSUE THREAD

**Issue by Alyaa-hamza** [Mohannadcse/IoTCOM#1]
@Mohannadcse  When I try to run the code on eclipse following the steps (IoTCOM_Behavioral Rule Extractor ) . i found the attached errors . I need to solve this problems. 

![Eclipse 1-1](https://user-images.githubusercontent.com/74778464/113623609-e2237980-965e-11eb-9871-ddd99aee7d05.jpg)
![Eclipse 1-2](https://user-images.githubusercontent.com/74778464/113623746-0da66400-965f-11eb-8e78-24d462ea94f3.jpg)
![Eclipse 1-3](https://user-images.githubusercontent.com/74778464/113624337-ca98c080-965f-11eb-9c9f-66dc20e7a4f2.jpg)

![Eclipse console error 1-4](https://user-images.githubusercontent.com/74778464/113624021-6b3ab080-965f-11eb-89d5-b200a1784f8b.jpg)

**Comment by Mohannadcse** [comment]
I don't recall I had such error. But make sure you're using java 1.7. Your Java compiler setting should be something like this
![image](https://user-images.githubusercontent.com/15859139/113795010-7d752700-9711-11eb-9e43-2e767421b173.png)

**Comment by Alyaa-hamza** [comment]
Thank you Dr.Mohannd for your fast reply . I will try to run the code with Java 1.7
