### ISSUE TITLE
IoTCOM errors from NetBeans

### ISSUE THREAD

**Issue by Alyaa-hamza** [Mohannadcse/IoTCOM#2]
@Mohannadcse .When i try also to run the code by using NetBeans , i found the following attached error . I think there is a missing repo. in the code . i will appreciate if you help me to solve this issue .

![NetBeans 1-1](https://user-images.githubusercontent.com/74778464/113625443-3cbdd500-9661-11eb-861e-ea50b321cdef.jpg)

**Comment by Mohannadcse** [comment]
I never tried netBeans, but the error says the output directory doesn't exist. Simply create a directory and call it `output`, something like this 
![image](https://user-images.githubusercontent.com/15859139/113795422-7a2e6b00-9712-11eb-9ae4-4d14ea4d6b12.png)

**Comment by Alyaa-hamza** [comment]
Thank you for your answer . I will try this step.
